unit UDFScripts;

interface

procedure CriarEstruturaBanco;

implementation

uses
  FireDAC.Comp.Client,
  PedidosData;

procedure CriarEstruturaBanco;
begin
  with dmPedidos.FDConexao do
  begin
    ExecSQL('PRAGMA foreign_keys = ON');

    ExecSQL('CREATE TABLE IF NOT EXISTS CLIENTES (' +
      'CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,' + 'NOME TEXT NOT NULL,' +
      'CIDADE TEXT,' + 'UF TEXT' + ')');

    ExecSQL('CREATE TABLE IF NOT EXISTS PRODUTOS (' +
      'CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,' + 'DESCRICAO TEXT NOT NULL,' +
      'PRECO_VENDA REAL' + ')');

    ExecSQL('CREATE TABLE IF NOT EXISTS PEDIDOS (' +
      'NUMERO_PEDIDO INTEGER PRIMARY KEY AUTOINCREMENT,' +
      'DATA_EMISSAO TEXT NOT NULL,' + 'CODIGO_CLIENTE INTEGER NOT NULL,' +
      'VALOR_TOTAL REAL,' +
      'FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO)' + ')');

    ExecSQL('CREATE TABLE IF NOT EXISTS PEDIDOS_ITENS (' +
      'ID INTEGER PRIMARY KEY AUTOINCREMENT,' +
      'NUMERO_PEDIDO INTEGER NOT NULL,' + 'CODIGO_PRODUTO INTEGER NOT NULL,' +
      'QUANTIDADE INTEGER NOT NULL,' + 'VALOR_UNITARIO REAL NOT NULL,' +
      'VALOR_TOTAL REAL NOT NULL,' +
      'FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDOS(NUMERO_PEDIDO),' +
      'FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTOS(CODIGO)' + ')');

    ExecSQL('CREATE INDEX IF NOT EXISTS IDX_PEDIDOS_CLIENTE ' +
      'ON PEDIDOS(CODIGO_CLIENTE)');

    ExecSQL('CREATE INDEX IF NOT EXISTS IDX_ITENS_PEDIDO ' +
      'ON PEDIDOS_ITENS(NUMERO_PEDIDO)');

    ExecSQL('CREATE INDEX IF NOT EXISTS IDX_ITENS_PRODUTO ' +
      'ON PEDIDOS_ITENS(CODIGO_PRODUTO)');
  end;
end;

end.
